site_name: Puroguramin
site_description: practical, anti-tutorial-hell focus on basics, problem-solving.
site_author: idk
repo_url: https://github.com/thu-tram/puroguramin
repo_name: Open a pull request

nav:
  - home:
    - 'homepage': 'index.md'
    - 'mindset': 'mindset.md'
    - 'programming fundamentals': 'start.md'
    - 'course recs for absolute beginners': 'course-recs.md'
  - guide:
    - 'main guide': 'guide.md'
    - 'start solving problems early': 'problems-early.md'
    - 'ask good questions': 'ask-good-questions.md'
    - 'read documentation': 'read-docs.md'
    - 'read other peoples code': 'read-code.md'
    - 'debugging': 'debugging.md'
    - 'planning': 'planning.md'
    - 'build your first real project': 'first-real-project.md'
    - 'basic project management': 'project-management.md'
    - 'keep a coding journal': 'coding-journal.md'
  - 'spaced repetition (janki)':
    - 'Part 1': 'janki1.md'
    - 'Part 2': 'janki2.md'
  - 'Resources':
    - 'Resources': 'resources.md' 


theme:
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: cyan 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  icon:
    repo: fontawesome/brands/github


markdown_extensions:
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
plugins:
  - search
  - open-in-new-tab

extra:
  generator: false